# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

put_na <- function(recon, pred) {
    .Call('_MetaPredict_put_na', PACKAGE = 'MetaPredict', recon, pred)
}

put_pred <- function(result, pred) {
    .Call('_MetaPredict_put_pred', PACKAGE = 'MetaPredict', result, pred)
}

reclassify <- function(result) {
    .Call('_MetaPredict_reclassify', PACKAGE = 'MetaPredict', result)
}

